apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: backend-tappi
          image: containerland.azurecr.io/backendtappi:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: backend-deployment
