apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-tappi
          image: arsenikki/untappi-backend:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: untappi-appi-very-secret-secret
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: backend
