apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: app.185.136.234.212.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend-service
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: back-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: api.185.136.234.212.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: backend-service
              servicePort: 80
