apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - untappiappi.westeurope.cloudapp.azure.com
      secretName: tls-secret
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: frontend-node-service
              servicePort: 80
          - path: /hello-world
            backend:
              serviceName: aks-helloworld
              servicePort: 80
          - path: /hello-world-two
            backend:
              serviceName: ingress-demo
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: back-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - untappiappi.westeurope.cloudapp.azure.com
      secretName: tls-secret
  rules:
    - http:
        paths:
          - path: /api(/|$)(.*)
            backend:
              serviceName: backend-node-service
              servicePort: 80
