apiVersion: v1
kind: Service
metadata:
  name: {{ include "untappi-appi.fullname" . }}
  labels:
    {{- include "untappi-appi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
  selector:
    {{- include "untappi-appi.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "untappi-appi.fullname" . }}
  labels:
    {{- include "untappi-appi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
  selector:
    {{- include "untappi-appi.selectorLabels" . | nindent 4 }}